from database import Table, Field

# all_fact = ["store_sales", "store_returns", "catalog_sales",
#             "catalog_returns", "web_sales", "web_returns",
#             "inventory"]
#
# all_dim = ["store", "call_center", "catalog_page", "web_site",
#            "web_page", "warehouse", "customer", "customer_address",
#            "customer_demographics", "date_dim", "household_demographics",
#            "item", "income_band", "promotion", "reason", "ship_mode",
#            "time_dim", "dsdgen_version"]
# all fact tables
# store_sales
store_sales = Table("store_sales", "f")

store_sales.addField(Field("ss_sold_date_sk", "identifier", "store_sales"))
store_sales.addField(Field("ss_sold_time_sk", "identifier", "store_sales"))
store_sales.addField(Field("ss_item_sk", "identifier", "store_sales"))
store_sales.addField(Field("ss_customer_sk", "identifier", "store_sales"))
store_sales.addField(Field("ss_cdemo_sk", "identifier", "store_sales"))
store_sales.addField(Field("ss_hdemo_sk", "identifier", "store_sales"))
store_sales.addField(Field("ss_addr_sk", "identifier", "store_sales"))
store_sales.addField(Field("ss_store_sk", "identifier", "store_sales"))
store_sales.addField(Field("ss_promo_sk", "identifier", "store_sales"))
store_sales.addField(Field("ss_ticket_number", "identifier", "store_sales"))
store_sales.addField(Field("ss_quantity", "integer", "store_sales"))
store_sales.addField(Field("ss_wholesale_cost", "decimal(7,2)", "store_sales"))
store_sales.addField(Field("ss_list_price", "decimal(7,2)", "store_sales"))
store_sales.addField(Field("ss_sales_price", "decimal(7,2)", "store_sales"))
store_sales.addField(Field("ss_ext_discount_amt", "decimal(7,2)", "store_sales"))
store_sales.addField(Field("ss_ext_sales_price", "decimal(7,2)", "store_sales"))
store_sales.addField(Field("ss_ext_wholesale_cost", "decimal(7,2)", "store_sales"))
store_sales.addField(Field("ss_ext_list_price", "decimal(7,2)", "store_sales"))
store_sales.addField(Field("ss_ext_tax", "decimal(7,2)", "store_sales"))
store_sales.addField(Field("ss_coupon_amt", "decimal(7,2)", "store_sales"))
store_sales.addField(Field("ss_net_paid", "decimal(7,2)", "store_sales"))
store_sales.addField(Field("ss_net_paid_inc_tax", "decimal(7,2)", "store_sales"))
store_sales.addField(Field("ss_net_profit", "decimal(7,2)", "store_sales"))

# store_returns
store_returns = Table("store_returns", "f")

store_returns.addField(Field("sr_returned_date_sk", "identifier", "store_returns"))
store_returns.addField(Field("sr_return_time_sk", "identifier", "store_returns"))
store_returns.addField(Field("sr_item_sk", "identifier", "store_returns"))
store_returns.addField(Field("sr_customer_sk", "identifier", "store_returns"))
store_returns.addField(Field("sr_cdemo_sk", "identifier", "store_returns"))
store_returns.addField(Field("sr_hdemo_sk", "identifier", "store_returns"))
store_returns.addField(Field("sr_addr_sk", "identifier", "store_returns"))
store_returns.addField(Field("sr_store_sk", "identifier", "store_returns"))
store_returns.addField(Field("sr_reason_sk", "identifier", "store_returns"))
store_returns.addField(Field("sr_ticket_number", "identifier", "store_returns"))
store_returns.addField(Field("sr_return_quantity", "integer", "store_returns"))
store_returns.addField(Field("sr_return_amt", "decimal(7,2)", "store_returns"))
store_returns.addField(Field("sr_return_tax", "decimal(7,2)", "store_returns"))
store_returns.addField(Field("sr_return_amt_inc_tax", "decimal(7,2)", "store_returns"))
store_returns.addField( Field("sr_fee", "decimal(7,2)", "store_returns"))
store_returns.addField(Field("sr_return_ship_cost", "decimal(7,2)", "store_returns"))
store_returns.addField(Field("sr_refunded_cash", "decimal(7,2)", "store_returns"))
store_returns.addField(Field("sr_reversed_charge", "decimal(7,2)", "store_returns"))
store_returns.addField(Field("sr_store_credit", "decimal(7,2)", "store_returns"))
store_returns.addField( Field("sr_net_loss", "decimal(7,2)", "store_returns"))



# catalog_sales
catalog_sales = Table("catalog_sales", "f")

catalog_sales.addField(Field("cs_sold_date_sk", "identifier", "catalog_sales"))
catalog_sales.addField(Field("cs_sold_time_sk", "identifier", "catalog_sales"))
catalog_sales.addField(Field("cs_ship_date_sk", "identifier", "catalog_sales"))
catalog_sales.addField(Field("cs_bill_customer_sk", "identifier", "catalog_sales"))
catalog_sales.addField(Field("cs_bill_cdemo_sk", "identifier", "catalog_sales"))
catalog_sales.addField(Field("cs_bill_hdemo_sk", "identifier", "catalog_sales"))
catalog_sales.addField(Field("cs_bill_addr_sk", "identifier", "catalog_sales"))
catalog_sales.addField(Field("cs_ship_customer_sk", "identifier", "catalog_sales"))
catalog_sales.addField(Field("cs_ship_cdemo_sk", "identifier", "catalog_sales"))
catalog_sales.addField(Field("cs_ship_hdemo_sk", "identifier", "catalog_sales"))
catalog_sales.addField(Field("cs_ship_addr_sk", "identifier", "catalog_sales"))
catalog_sales.addField(Field("cs_call_center_sk", "identifier", "catalog_sales"))
catalog_sales.addField(Field("cs_catalog_page_sk", "identifier", "catalog_sales"))
catalog_sales.addField(Field("cs_ship_mode_sk", "identifier", "catalog_sales"))
catalog_sales.addField(Field("cs_warehouse_sk", "identifier", "catalog_sales"))
catalog_sales.addField(Field("cs_item_sk", "identifier", "catalog_sales"))
catalog_sales.addField(Field("cs_promo_sk", "identifier", "catalog_sales"))
catalog_sales.addField(Field("cs_order_number", "identifier", "catalog_sales"))
catalog_sales.addField(Field("cs_quantity", "integer", "catalog_sales"))
catalog_sales.addField(Field("cs_wholesale_cost", "decimal(7,2)", "catalog_sales"))
catalog_sales.addField(Field("cs_list_price", "decimal(7,2)", "catalog_sales"))
catalog_sales.addField(Field("cs_sales_price", "decimal(7,2)", "catalog_sales"))
catalog_sales.addField(Field("cs_ext_discount_amt", "decimal(7,2)", "catalog_sales"))
catalog_sales.addField(Field("cs_ext_sales_price", "decimal(7,2)", "catalog_sales"))
catalog_sales.addField(Field("cs_ext_wholesale_cost", "decimal(7,2)", "catalog_sales"))
catalog_sales.addField(Field("cs_ext_list_price", "decimal(7,2)", "catalog_sales"))
catalog_sales.addField(Field("cs_ext_tax", "decimal(7,2)", "catalog_sales"))
catalog_sales.addField(Field("cs_coupon_amt", "decimal(7,2)", "catalog_sales"))
catalog_sales.addField(Field("cs_ext_ship_cost", "decimal(7,2)", "catalog_sales"))
catalog_sales.addField(Field("cs_net_paid", "decimal(7,2)", "catalog_sales"))
catalog_sales.addField(Field("cs_net_paid_inc_tax", "decimal(7,2)", "catalog_sales"))
catalog_sales.addField(Field("cs_net_paid_inc_ship", "decimal(7,2)", "catalog_sales"))
catalog_sales.addField(Field("cs_net_paid_inc_ship_tax", "decimal(7,2)", "catalog_sales"))
catalog_sales.addField(Field("cs_net_profit", "decimal(7,2)", "catalog_sales"))

# catalog_returns
catalog_sales = Table("catalog_sales", "f")
# Field initializations
cs_sold_date_sk = Field("cs_sold_date_sk", "identifier", "catalog_sales")
cs_sold_time_sk = Field("cs_sold_time_sk", "identifier", "catalog_sales")
cs_ship_date_sk = Field("cs_ship_date_sk", "identifier", "catalog_sales")
cs_bill_customer_sk = Field("cs_bill_customer_sk", "identifier", "catalog_sales")
cs_bill_cdemo_sk = Field("cs_bill_cdemo_sk", "identifier", "catalog_sales")
cs_bill_hdemo_sk = Field("cs_bill_hdemo_sk", "identifier", "catalog_sales")
cs_bill_addr_sk = Field("cs_bill_addr_sk", "identifier", "catalog_sales")
cs_ship_customer_sk = Field("cs_ship_customer_sk", "identifier", "catalog_sales")
cs_ship_cdemo_sk = Field("cs_ship_cdemo_sk", "identifier", "catalog_sales")
cs_ship_hdemo_sk = Field("cs_ship_hdemo_sk", "identifier", "catalog_sales")
cs_ship_addr_sk = Field("cs_ship_addr_sk", "identifier", "catalog_sales")
cs_call_center_sk = Field("cs_call_center_sk", "identifier", "catalog_sales")
cs_catalog_page_sk = Field("cs_catalog_page_sk", "identifier", "catalog_sales")
cs_ship_mode_sk = Field("cs_ship_mode_sk", "identifier", "catalog_sales")
cs_warehouse_sk = Field("cs_warehouse_sk", "identifier", "catalog_sales")
cs_item_sk = Field("cs_item_sk", "identifier", "catalog_sales")
cs_promo_sk = Field("cs_promo_sk", "identifier", "catalog_sales")
cs_order_number = Field("cs_order_number", "identifier", "catalog_sales")
cs_quantity = Field("cs_quantity", "integer", "catalog_sales")
cs_wholesale_cost = Field("cs_wholesale_cost", "decimal(7,2)", "catalog_sales")
cs_list_price = Field("cs_list_price", "decimal(7,2)", "catalog_sales")
cs_sales_price = Field("cs_sales_price", "decimal(7,2)", "catalog_sales")
cs_ext_discount_amt = Field("cs_ext_discount_amt", "decimal(7,2)", "catalog_sales")
cs_ext_sales_price = Field("cs_ext_sales_price", "decimal(7,2)", "catalog_sales")
cs_ext_wholesale_cost = Field("cs_ext_wholesale_cost", "decimal(7,2)", "catalog_sales")
cs_ext_list_price = Field("cs_ext_list_price", "decimal(7,2)", "catalog_sales")
cs_ext_tax = Field("cs_ext_tax", "decimal(7,2)", "catalog_sales")
cs_coupon_amt = Field("cs_coupon_amt", "decimal(7,2)", "catalog_sales")
cs_ext_ship_cost = Field("cs_ext_ship_cost", "decimal(7,2)", "catalog_sales")
cs_net_paid = Field("cs_net_paid", "decimal(7,2)", "catalog_sales")
cs_net_paid_inc_tax = Field("cs_net_paid_inc_tax", "decimal(7,2)", "catalog_sales")
cs_net_paid_inc_ship = Field("cs_net_paid_inc_ship", "decimal(7,2)", "catalog_sales")
cs_net_paid_inc_ship_tax = Field("cs_net_paid_inc_ship_tax", "decimal(7,2)", "catalog_sales")
cs_net_profit = Field("cs_net_profit", "decimal(7,2)", "catalog_sales")

# Add fields to catalog_sales
catalog_sales.addField(cs_sold_date_sk)
catalog_sales.addField(cs_sold_time_sk)
catalog_sales.addField(cs_ship_date_sk)
catalog_sales.addField(cs_bill_customer_sk)
catalog_sales.addField(cs_bill_cdemo_sk)
catalog_sales.addField(cs_bill_hdemo_sk)
catalog_sales.addField(cs_bill_addr_sk)
catalog_sales.addField(cs_ship_customer_sk)
catalog_sales.addField(cs_ship_cdemo_sk)
catalog_sales.addField(cs_ship_hdemo_sk)
catalog_sales.addField(cs_ship_addr_sk)
catalog_sales.addField(cs_call_center_sk)
catalog_sales.addField(cs_catalog_page_sk)
catalog_sales.addField(cs_ship_mode_sk)
catalog_sales.addField(cs_warehouse_sk)
catalog_sales.addField(cs_item_sk)
catalog_sales.addField(cs_promo_sk)
catalog_sales.addField(cs_order_number)
catalog_sales.addField(cs_quantity)
catalog_sales.addField(cs_wholesale_cost)
catalog_sales.addField(cs_list_price)
catalog_sales.addField(cs_sales_price)
catalog_sales.addField(cs_ext_discount_amt)
catalog_sales.addField(cs_ext_sales_price)
catalog_sales.addField(cs_ext_wholesale_cost)
catalog_sales.addField(cs_ext_list_price)
catalog_sales.addField(cs_ext_tax)
catalog_sales.addField(cs_coupon_amt)
catalog_sales.addField(cs_ext_ship_cost)
catalog_sales.addField(cs_net_paid)
catalog_sales.addField(cs_net_paid_inc_tax)
catalog_sales.addField(cs_net_paid_inc_ship)
catalog_sales.addField(cs_net_paid_inc_ship_tax)
catalog_sales.addField(cs_net_profit)

# web_sales
web_sales = Table("web_sales", "f")
web_sales.addField(Field("ws_sold_date_sk", "identifier", "web_sales"))
web_sales.addField(Field("ws_sold_time_sk", "identifier", "web_sales"))
web_sales.addField(Field("ws_ship_date_sk", "identifier", "web_sales"))
web_sales.addField(Field("ws_item_sk", "identifier", "web_sales"))
web_sales.addField(Field("ws_bill_customer_sk", "identifier", "web_sales"))
web_sales.addField(Field("ws_bill_cdemo_sk", "identifier", "web_sales"))
web_sales.addField(Field("ws_bill_hdemo_sk", "identifier", "web_sales"))
web_sales.addField(Field("ws_bill_addr_sk", "identifier", "web_sales"))
web_sales.addField(Field("ws_ship_customer_sk", "identifier", "web_sales"))
web_sales.addField(Field("ws_ship_cdemo_sk", "identifier", "web_sales"))
web_sales.addField(Field("ws_ship_hdemo_sk", "identifier", "web_sales"))
web_sales.addField(Field("ws_ship_addr_sk", "identifier", "web_sales"))
web_sales.addField(Field("ws_web_page_sk", "identifier", "web_sales"))
web_sales.addField(Field("ws_web_site_sk", "identifier", "web_sales"))
web_sales.addField(Field("ws_ship_mode_sk", "identifier", "web_sales"))
web_sales.addField(Field("ws_warehouse_sk", "identifier", "web_sales"))
web_sales.addField(Field("ws_promo_sk", "identifier", "web_sales"))
web_sales.addField(Field("ws_order_number", "identifier", "web_sales"))
web_sales.addField(Field("ws_quantity", "integer", "web_sales"))
web_sales.addField(Field("ws_wholesale_cost", "decimal(7,2)", "web_sales"))
web_sales.addField(Field("ws_list_price", "decimal(7,2)", "web_sales"))
web_sales.addField(Field("ws_sales_price", "decimal(7,2)", "web_sales"))
web_sales.addField(Field("ws_ext_discount_amt", "decimal(7,2)", "web_sales"))
web_sales.addField(Field("ws_ext_sales_price", "decimal(7,2)", "web_sales"))
web_sales.addField(Field("ws_ext_wholesale_cost", "decimal(7,2)", "web_sales"))
web_sales.addField(Field("ws_ext_list_price", "decimal(7,2)", "web_sales"))
web_sales.addField(Field("ws_ext_tax", "decimal(7,2)", "web_sales"))
web_sales.addField(Field("ws_coupon_amt", "decimal(7,2)", "web_sales"))
web_sales.addField(Field("ws_ext_ship_cost", "decimal(7,2)", "web_sales"))
web_sales.addField(Field("ws_net_paid", "decimal(7,2)", "web_sales"))
web_sales.addField(Field("ws_net_paid_inc_tax", "decimal(7,2)", "web_sales"))
web_sales.addField(Field("ws_net_paid_inc_ship", "decimal(7,2)", "web_sales"))
web_sales.addField(Field("ws_net_paid_inc_ship_tax", "decimal(7,2)", "web_sales"))
web_sales.addField(Field("ws_net_profit", "decimal(7,2)", "web_sales"))
# web_returns
web_returns = Table("web_returns", "f")
web_returns.addField(Field("wr_returned_date_sk", "identifier", "web_returns"))
web_returns.addField(Field("wr_returned_time_sk", "identifier", "web_returns"))
web_returns.addField(Field("wr_item_sk", "(1)", "web_returns"))
web_returns.addField(Field("wr_refunded_customer_sk", "identifier", "web_returns"))
web_returns.addField(Field("wr_refunded_cdemo_sk", "identifier", "web_returns"))
web_returns.addField(Field("wr_refunded_hdemo_sk", "identifier", "web_returns"))
web_returns.addField(Field("wr_refunded_addr_sk", "identifier", "web_returns"))
web_returns.addField(Field("wr_returning_customer_sk", "identifier", "web_returns"))
web_returns.addField(Field("wr_returning_cdemo_sk", "identifier", "web_returns"))
web_returns.addField(Field("wr_returning_hdemo_sk", "identifier", "web_returns"))
web_returns.addField(Field("wr_returning_addr_sk", "identifier", "web_returns"))
web_returns.addField(Field("wr_web_page_sk", "identifier", "web_returns"))
web_returns.addField(Field("wr_reason_sk", "identifier", "web_returns"))
web_returns.addField(Field("wr_order_number", "identifier", "web_returns"))
web_returns.addField(Field("wr_return_quantity", "integer", "web_returns"))
web_returns.addField(Field("wr_return_amt", "decimal(7,2)", "web_returns"))
web_returns.addField(Field("wr_return_tax", "decimal(7,2)", "web_returns"))
web_returns.addField(Field("wr_return_amt_inc_tax", "decimal(7,2)", "web_returns"))
web_returns.addField(Field("wr_fee", "decimal(7,2)", "web_returns"))
web_returns.addField(Field("wr_return_ship_cost", "decimal(7,2)", "web_returns"))
web_returns.addField(Field("wr_refunded_cash", "decimal(7,2)", "web_returns"))
web_returns.addField(Field("wr_reversed_charge", "decimal(7,2)", "web_returns"))
web_returns.addField(Field("wr_account_credit", "decimal(7,2)", "web_returns"))
web_returns.addField(Field("wr_net_loss", "decimal(7,2)", "web_returns"))
# inventory
inventory = Table("inventory", "f")
inventory.addField(Field("inv_date_sk", "(1)", "inventory"))
inventory.addField(Field("inv_item_sk", "identifier", "inventory"))
inventory.addField(Field("inv_warehouse_sk", "identifier", "inventory"))
inventory.addField(Field("inv_quantity_on_hand", "integer", "inventory"))

# all dim table
date_dim = Table("date_dim", "d")
date_dim.addField(Field("d_date_sk", "identifier", "date_dim"))
date_dim.addField(Field("d_date_id", "char(16)", "date_dim"))
date_dim.addField(Field("d_date", "date", "date_dim"))
date_dim.addField(Field("d_month_seq", "integer", "date_dim"))
date_dim.addField(Field("d_week_seq", "integer", "date_dim"))
date_dim.addField(Field("d_quarter_seq", "integer", "date_dim"))
date_dim.addField(Field("d_year", "integer", "date_dim"))
date_dim.addField(Field("d_dow", "integer", "date_dim"))
date_dim.addField(Field("d_moy", "integer", "date_dim"))
date_dim.addField(Field("d_dom", "integer", "date_dim"))
date_dim.addField(Field("d_qoy", "integer", "date_dim"))
date_dim.addField(Field("d_fy_year", "integer", "date_dim"))
date_dim.addField(Field("d_fy_quarter_seq", "integer", "date_dim"))
date_dim.addField(Field("d_fy_week_seq", "integer", "date_dim"))
date_dim.addField(Field("d_day_name ", "char(9)", "date_dim"))
date_dim.addField(Field("d_quarter_name ", "char(1)", "date_dim"))
date_dim.addField(Field("d_holiday ", "char(1)", "date_dim"))
date_dim.addField(Field("d_weekend", "char(1)", "date_dim"))
date_dim.addField(Field("d_following_holiday", "char(1)", "date_dim"))
date_dim.addField(Field("d_first_dom", "integer", "date_dim"))
date_dim.addField(Field("d_last_dom", "integer", "date_dim"))
date_dim.addField(Field("d_same_day_ly", "integer", "date_dim"))
date_dim.addField(Field("d_same_day_lq", "integer", "date_dim"))
date_dim.addField(Field("d_current_day", "char(1)", "date_dim"))
date_dim.addField(Field("d_current_week", "char(1)", "date_dim"))
date_dim.addField(Field("d_current_month ", "char(1)", "date_dim"))
date_dim.addField(Field("d_current_quarter", "char(1)", "date_dim"))
date_dim.addField(Field("d_current_year", "char(1)", "date_dim"))
date_dim.join_field_str="d_date_sk"
# store
store = Table("store", "d")
store.addField(Field("s_store_sk", "identifier", "store"))
store.addField(Field("s_store_id", "char(16)", "store"))
store.addField(Field("s_rec_start_date", "date", "store"))
store.addField(Field("s_rec_end_date", "date", "store"))
store.addField(Field("s_closed_date_sk", "identifier", "store"))
store.addField(Field("s_store_name", "varchar(50)", "store"))
store.addField(Field("s_number_employees", "integer", "store"))
store.addField(Field("s_floor_space", "integer", "store"))
store.addField(Field("s_hours", "char(20)", "store"))
store.addField(Field("S_manager", "varchar(40)", "store"))
store.addField(Field("S_market_id", "integer", "store"))
store.addField(Field("S_geography_class", "varchar(100)", "store"))
store.addField(Field("S_market_desc", "varchar(100)", "store"))
store.addField(Field("s_market_manager", "varchar(40)", "store"))
store.addField(Field("s_division_id", "integer", "store"))
store.addField(Field("s_division_name", "varchar(50)", "store"))
store.addField(Field("s_company_id", "integer", "store"))
store.addField(Field("s_company_name", "varchar(50)", "store"))
store.addField(Field("s_street_number", "varchar(10)", "store"))
store.addField(Field("s_street_name", "varchar(60)", "store"))
store.addField(Field("s_street_type", "char(15)", "store"))
store.addField(Field("s_suite_number", "char(10)", "store"))
store.addField(Field("s_city", "varchar(60)", "store"))
store.addField(Field("s_county", "varchar(30)", "store"))
store.addField(Field("s_state", "char(2)", "store"))
store.addField(Field("s_zip", "char(10)", "store"))
store.addField(Field("s_country", "varchar(20)", "store"))
store.addField(Field("s_gmt_offset", "decimal(5,2)", "store"))
store.addField(Field("s_tax_percentage", "decimal(5,2)", "store"))
# call_center
call_center = Table("call_center", "d")
call_center.addField(Field("cc_call_center_sk", "identifier", "call_center"))
call_center.addField(Field("cc_call_center_id", "char(16)", "call_center"))
call_center.addField(Field("cc_rec_start_date", "date", "call_center"))
call_center.addField(Field("cc_rec_end_date", "date", "call_center"))
call_center.addField(Field("cc_closed_date_sk", "identifier", "call_center"))
call_center.addField(Field("cc_open_date_sk", "identifier", "call_center"))
call_center.addField(Field("cc_name", "varchar(50)", "call_center"))
call_center.addField(Field("cc_class", "varchar(50)", "call_center"))
call_center.addField(Field("cc_employees", "integer", "call_center"))
call_center.addField(Field("cc_sq_ft", "integer", "call_center"))
call_center.addField(Field("cc_hours", "char(20)", "call_center"))
call_center.addField(Field("cc_manager", "varchar(40)", "call_center"))
call_center.addField(Field("cc_mkt_id", "integer", "call_center"))
call_center.addField(Field("cc_mkt_class", "char(50)", "call_center"))
call_center.addField(Field("cc_mkt_desc", "varchar(100)", "call_center"))
call_center.addField(Field("cc_market_manager", "varchar(40)", "call_center"))
call_center.addField(Field("cc_division", "integer", "call_center"))
call_center.addField(Field("cc_division_name", "varchar(50)", "call_center"))
call_center.addField(Field("cc_company", "integer", "call_center"))
call_center.addField(Field("cc_company_name", "char(50)", "call_center"))
call_center.addField(Field("cc_street_number", "char(10)", "call_center"))
call_center.addField(Field("cc_street_name", "varchar(60)", "call_center"))
call_center.addField(Field("cc_street_type", "char(15)", "call_center"))
call_center.addField(Field("cc_suite_number", "char(10)", "call_center"))
call_center.addField(Field("cc_city", "varchar(60)", "call_center"))
call_center.addField(Field("cc_county", "varchar(30)", "call_center"))
call_center.addField(Field("cc_state", "char(2)", "call_center"))
call_center.addField(Field("cc_zip", "char(10)", "call_center"))
call_center.addField(Field("cc_country", "varchar(20)", "call_center"))
call_center.addField(Field("cc_gmt_offset", "decimal(5,2)", "call_center"))
call_center.addField(Field("cc_tax_percentage", "decimal(5,2)", "call_center"))
# catalog_page
catalog_page = Table("catalog_page", "d")
catalog_page.addField(Field("cp_catalog_page_sk", "identifier", "catalog_page"))
catalog_page.addField(Field("cp_catalog_page_id", "char(16)", "catalog_page"))
catalog_page.addField(Field("cp_start_date_sk", "identifier", "catalog_page"))
catalog_page.addField(Field("cp_end_date_sk", "identifier", "catalog_page"))
catalog_page.addField(Field("cp_department", "varchar(50)", "catalog_page"))
catalog_page.addField(Field("cp_catalog_number", "integer", "catalog_page"))
catalog_page.addField(Field("cp_catalog_page_number", "integer", "catalog_page"))
catalog_page.addField(Field("cp_description", "varchar(100)", "catalog_page"))
catalog_page.addField(Field("cp_type", "varchar(100)", "catalog_page"))
# web_site
web_site = Table("web_site", "d")
web_site.addField(Field("web_site_sk", "identifier", "web_site"))
web_site.addField(Field("web_site_id", "(B)", "web_site"))
web_site.addField(Field("web_rec_start_date", "date", "web_site"))
web_site.addField(Field("web_rec_end_date", "date", "web_site"))
web_site.addField(Field("web_name", "varchar(50)", "web_site"))
web_site.addField(Field("web_open_date_sk", "identifier", "web_site"))
web_site.addField(Field("web_close_date_sk", "identifier", "web_site"))
web_site.addField(Field("web_class", "varchar(50)", "web_site"))
web_site.addField(Field("web_manager", "varchar(40)", "web_site"))
web_site.addField(Field("web_mkt_id", "integer", "web_site"))
web_site.addField(Field("web_mkt_class", "varchar(50)", "web_site"))
web_site.addField(Field("web_mkt_desc", "varchar(100)", "web_site"))
web_site.addField(Field("web_market_manager", "varchar(40)", "web_site"))
web_site.addField(Field("web_company_id", "integer", "web_site"))
web_site.addField(Field("web_company_name", "char(50)", "web_site"))
web_site.addField(Field("web_street_number", "char(10)", "web_site"))
web_site.addField(Field("web_street_name", "varchar(60)", "web_site"))
web_site.addField(Field("web_street_type", "char(15)", "web_site"))
web_site.addField(Field("web_suite_number", "char(10)", "web_site"))
web_site.addField(Field("web_city", "varchar(60)", "web_site"))
web_site.addField(Field("web_county", "varchar(30)", "web_site"))
web_site.addField(Field("web_state", "char(2)", "web_site"))
web_site.addField(Field("web_zip", "char(10)", "web_site"))
web_site.addField(Field("web_country", "varchar(20)", "web_site"))
web_site.addField(Field("web_gmt_offset", "decimal(5,2)", "web_site"))
web_site.addField(Field("web_tax_percentage", "decimal(5,2)", "web_site"))
# web_page
web_page = Table("web_page", "d")
web_page.addField(Field("wp_web_page_sk", "identifier", "web_page"))
web_page.addField(Field("wp_web_page_id", "char(16)", "web_page"))
web_page.addField(Field("wp_rec_start_date", "date", "web_page"))
web_page.addField(Field("wp_rec_end_date", "date", "web_page"))
web_page.addField(Field("wp_creation_date_sk", "identifier", "web_page"))
web_page.addField(Field("wp_access_date_sk", "identifier", "web_page"))
web_page.addField(Field("wp_autogen_flag", "char(1)", "web_page"))
web_page.addField(Field("wp_customer_sk", "identifier", "web_page"))
web_page.addField(Field("wp_url", "varchar(100)", "web_page"))
web_page.addField(Field("wp_type", "char(50)", "web_page"))
web_page.addField(Field("wp_char_count", "integer", "web_page"))
web_page.addField(Field("wp_link_count", "integer", "web_page"))
web_page.addField(Field("wp_image_count", "integer", "web_page"))
web_page.addField(Field("wp_max_ad_count", "integer", "web_page"))
# warehouse
warehouse = Table("warehouse", "d")
warehouse.addField(Field("w_warehouse_sk", "identifier", "warehouse"))
warehouse.addField(Field("w_warehouse_id", "char(16)", "warehouse"))
warehouse.addField(Field("w_warehouse_name", "varchar(20)", "warehouse"))
warehouse.addField(Field("w_warehouse_sq_ft", "integer", "warehouse"))
warehouse.addField(Field("w_street_number", "char(10)", "warehouse"))
warehouse.addField(Field("w_street_name", "varchar(60)", "warehouse"))
warehouse.addField(Field("w_street_type", "char(15)", "warehouse"))
warehouse.addField(Field("w_suite_number", "char(10)", "warehouse"))
warehouse.addField(Field("w_city", "varchar(60)", "warehouse"))
warehouse.addField(Field("w_county", "varchar(30)", "warehouse"))
warehouse.addField(Field("w_state", "char(2)", "warehouse"))
warehouse.addField(Field("w_zip", "char(10)", "warehouse"))
warehouse.addField(Field("w_country", "varchar(20)", "warehouse"))
warehouse.addField(Field("w_gmt_offset", "decimal(5,2)", "warehouse"))
# customer
customer = Table("customer", "d")
customer.addField(Field("c_customer_sk", "identifier", "customer"))
customer.addField(Field("c_customer_id", "char(16)", "customer"))
customer.addField(Field("c_current_cdemo_sk", "identifier", "customer"))
customer.addField(Field("c_current_hdemo_sk", "identifier", "customer"))
customer.addField(Field("c_current_addr_sk", "identifier", "customer"))
customer.addField(Field("c_first_shipto_date_sk", "identifier", "customer"))
customer.addField(Field("c_first_sales_date_sk", "identifier", "customer"))
customer.addField(Field("c_salutation", "char(10)", "customer"))
customer.addField(Field("c_first_name", "char(20)", "customer"))
customer.addField(Field("c_last_name", "char(30)", "customer"))
customer.addField(Field("c_preferred_cust_flag", "char(1)", "customer"))
customer.addField(Field("c_birth_day", "integer", "customer"))
customer.addField(Field("c_birth_month", "integer", "customer"))
customer.addField(Field("c_birth_year", "integer", "customer"))
customer.addField(Field("c_birth_country", "varchar(20)", "customer"))
customer.addField(Field("c_login", "char(13)", "customer"))
customer.addField(Field("c_email_address", "char(50)", "customer"))
customer.addField(Field("c_last_review_date_sk", "identifier", "customer"))
# customer_address
customer_address = Table("customer_address", "d")
customer_address.addField(Field("ca_address_sk", "identifier", "customer_address"))
customer_address.addField(Field("ca_address_id", "char(16)", "customer_address"))
customer_address.addField(Field("ca_street_number", "char(10)", "customer_address"))
customer_address.addField(Field("ca_street_name", "varchar(60)", "customer_address"))
customer_address.addField(Field("ca_street_type", "char(15)", "customer_address"))
customer_address.addField(Field("ca_suite_number", "char(10)", "customer_address"))
customer_address.addField(Field("ca_city", "varchar(60)", "customer_address"))
customer_address.addField(Field("ca_county", "varchar(30)", "customer_address"))
customer_address.addField(Field("ca_state", "char(2)", "customer_address"))
customer_address.addField(Field("ca_zip", "char(10)", "customer_address"))
customer_address.addField(Field("ca_country", "varchar(20)", "customer_address"))
customer_address.addField(Field("ca_gmt_offset", "decimal(5,2)", "customer_address"))
customer_address.addField(Field("ca_location_type", "char(20)", "customer_address"))
# customer_demographics
customer_demographics = Table("customer_demographics", "d")
customer_demographics.addField(Field("cd_demo_sk", "identifier", "customer_demographics"))
customer_demographics.addField(Field("cd_gender", "char(1)", "customer_demographics"))
customer_demographics.addField(Field("cd_marital_status", "char(1)", "customer_demographics"))
customer_demographics.addField(Field("cd_education_status", "char(20)", "customer_demographics"))
customer_demographics.addField(Field("cd_purchase_estimate", "integer", "customer_demographics"))
customer_demographics.addField(Field("cd_credit_rating", "char(10)", "customer_demographics"))
customer_demographics.addField(Field("cd_dep_count", "integer", "customer_demographics"))
customer_demographics.addField(Field("cd_dep_employed_count", "integer", "customer_demographics"))
customer_demographics.addField(Field("cd_dep_college_count", "integer", "customer_demographics"))
# household_demographics
household_demographics = Table("household_demographics", "d")
household_demographics.addField(Field("hd_demo_sk", "identifier", "household_demographics"))
household_demographics.addField(Field("hd_income_band_sk", "identifier", "household_demographics"))
household_demographics.addField(Field("hd_buy_potential", "char(15)", "household_demographics"))
household_demographics.addField(Field("hd_dep_count", "integer", "household_demographics"))
household_demographics.addField(Field("hd_vehicle_count", "integer", "household_demographics"))
# item
item = Table("item", "d")
item.addField(Field("i_item_sk", "identifier", "item"))
item.addField(Field("i_item_id", "(B)", "item"))
item.addField(Field("i_rec_start_date", "date", "item"))
item.addField(Field("i_rec_end_date", "date", "item"))
item.addField(Field("i_item_desc", "varchar(200)", "item"))
item.addField(Field("i_current_price", "decimal(7,2)", "item"))
item.addField(Field("i_wholesale_cost", "decimal(7,2)", "item"))
item.addField(Field("i_brand_id", "integer", "item"))
item.addField(Field("i_brand", "char(50)", "item"))
item.addField(Field("i_class_id", "integer", "item"))
item.addField(Field("i_class", "char(50)", "item"))
item.addField(Field("i_category_id", "integer", "item"))
item.addField(Field("i_category", "char(50)", "item"))
item.addField(Field("i_manufact_id", "integer", "item"))
item.addField(Field("i_manufact", "char(50)", "item"))
item.addField(Field("i_size", "char(20)", "item"))
item.addField(Field("i_formulation", "char(20)", "item"))
item.addField(Field("i_color", "char(20)", "item"))
item.addField(Field("i_units", "char(10)", "item"))
item.addField(Field("i_container", "char(10)", "item"))
item.addField(Field("i_manager_id", "integer", "item"))
item.addField(Field("i_product_name", "char(50)", "item"))
# income_band
income_band = Table("income_band", "d")
income_band.addField(Field("ib_income_band_sk", "identifier", "income_band"))
income_band.addField(Field("ib_lower_bound", "integer", "income_band"))
income_band.addField(Field("ib_upper_bound", "integer", "income_band"))
# promotion
promotion = Table("promotion", "d")
promotion.addField(Field("p_promo_sk", "identifier", "promotion"))
promotion.addField(Field("p_promo_id", "char(16)", "promotion"))
promotion.addField(Field("p_start_date_sk", "identifier", "promotion"))
promotion.addField(Field("p_end_date_sk", "identifier", "promotion"))
promotion.addField(Field("p_item_sk", "identifier", "promotion"))
promotion.addField(Field("p_cost", "decimal(15,2)", "promotion"))
promotion.addField(Field("p_response_target", "integer", "promotion"))
promotion.addField(Field("p_promo_name", "char(50)", "promotion"))
promotion.addField(Field("p_channel_dmail", "char(1)", "promotion"))
promotion.addField(Field("p_channel_email", "char(1)", "promotion"))
promotion.addField(Field("p_channel_catalog", "char(1)", "promotion"))
promotion.addField(Field("p_channel_tv", "char(1)", "promotion"))
promotion.addField(Field("p_channel_radio", "char(1)", "promotion"))
promotion.addField(Field("p_channel_press", "char(1)", "promotion"))
promotion.addField(Field("p_channel_event", "char(1)", "promotion"))
promotion.addField(Field("p_channel_demo", "char(1)", "promotion"))
promotion.addField(Field("p_channel_details", "varchar(100)", "promotion"))
promotion.addField(Field("p_purpose", "char(15)", "promotion"))
promotion.addField(Field("p_discount_active", "char(1)", "promotion"))
# reason
reason = Table("reason", "d")
reason.addField(Field("r_reason_sk", "identifier", "reason"))
reason.addField(Field("r_reason_id", "char(16)", "reason"))
reason.addField(Field("r_reason_desc", "char(100)", "reason"))
# ship_mode
ship_mode = Table("ship_mode", "d")
ship_mode.addField(Field("sm_ship_mode_sk", "identifier", "ship_mode"))
ship_mode.addField(Field("sm_ship_mode_id", "char(16)", "ship_mode"))
ship_mode.addField(Field("sm_type", "char(30)", "ship_mode"))
ship_mode.addField(Field("sm_code", "char(10)", "ship_mode"))
ship_mode.addField(Field("sm_carrier", "char(20)", "ship_mode"))
ship_mode.addField(Field("sm_contract", "char(20)", "ship_mode"))
# time_dim
time_dim = Table("time_dim", "d")
time_dim.addField(Field("t_time_sk", "Identifier", "time_dim"))
time_dim.addField(Field("t_time_id", "char(16)", "time_dim"))
time_dim.addField(Field("t_time", "Integer", "time_dim"))
time_dim.addField(Field("t_hour", "Integer", "time_dim"))
time_dim.addField(Field("t_minute", "Integer", "time_dim"))
time_dim.addField(Field("t_second", "Integer", "time_dim"))
time_dim.addField(Field("t_am_pm", "char(2)", "time_dim"))
time_dim.addField(Field("t_shift", "char(20)", "time_dim"))
time_dim.addField(Field("t_sub_shift", "char(20)", "time_dim"))
time_dim.addField(Field("t_meal_time", "char(20)", "time_dim"))
# dsdgen_version
dsdgen_version = Table("dsdgen_version", "d")
dsdgen_version.addField(Field("dv_version", "Varchar(16)", "dsdgen_version"))
dsdgen_version.addField(Field("dv_create_date", "date", "dsdgen_version"))
dsdgen_version.addField(Field("dv_create_time", "time", "dsdgen_version"))
dsdgen_version.addField(Field("dv_cmdline_args", "Varchar(200)", "dsdgen_version"))

# add relationship
store_sales.addRelationship(date_dim, "ss_sold_date_sk", "d_date_sk")
store_sales.addRelationship(time_dim, "ss_sold_time_sk", "t_time_sk")
store_sales.addRelationship(item, "ss_item_sk", "i_item_sk")
store_sales.addRelationship(customer, "ss_customer_sk", "c_customer_sk")
store_sales.addRelationship(customer_demographics, "ss_cdemo_sk", "cd_demo_sk")
store_sales.addRelationship(household_demographics, "ss_hdemo_sk", "hd_demo_sk")
store_sales.addRelationship(customer_address, "ss_addr_sk", "ca_address_sk")
store_sales.addRelationship(store, "ss_store_sk", "s_store_sk")
store_sales.addRelationship(promotion, "ss_promo_sk", "p_promo_sk")

store_returns.addRelationship(date_dim, "sr_returned_date_sk", "d_date_sk")
store_returns.addRelationship(time_dim, "sr_return_time_sk", "t_time_sk")
store_returns.addRelationship(item, "sr_item_sk", "i_item_sk")
store_returns.addRelationship(customer, "sr_customer_sk", "c_customer_sk")
store_returns.addRelationship(customer_demographics, "sr_cdemo_sk", "cd_demo_sk")
store_returns.addRelationship(household_demographics, "sr_hdemo_sk", "hd_demo_sk")
store_returns.addRelationship(customer_address, "sr_addr_sk", "ca_address_sk")
store_returns.addRelationship(reason, "sr_reason_sk", "r_reason_sk")
store_returns.addRelationship(store_sales, "sr_ticket_number", "ss_ticket_number")
